inherited dlgAreaWizard: TdlgAreaWizard
  Tag = 7
  Left = 558
  Top = 157
  Caption = 'Area Wizard'
  ClientHeight = 387
  ClientWidth = 366
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 13
  inherited bvDivider: TBevel
    Top = 343
    Width = 354
  end
  inherited bHelp: TButton
    Left = 12
    Top = 355
    TabOrder = 5
  end
  inherited bFinish: TButton
    Left = 204
    Top = 355
    TabOrder = 3
  end
  inherited bNext: TButton
    Left = 124
    Top = 355
    Height = 26
    TabOrder = 2
  end
  inherited bBack: TButton
    Left = 44
    Top = 355
    TabOrder = 1
  end
  inherited bCancel: TButton
    Left = 284
    Top = 355
    TabOrder = 4
  end
  inherited pcSteps: TPageControl
    Width = 366
    Height = 340
    ActivePage = tsFinish
    TabOrder = 0
    object tsNameAndTileSet: TTabSheet
      Tag = -1
      OnShow = tsNameAndTilesetShow
      object lTitleNameAndTileset: TLabel
        Tag = 8
        Left = 12
        Top = 12
        Width = 140
        Height = 20
        Caption = 'Name and Tileset'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'MS Sans Serif'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lDescriptionNameAndTileSet: TLabel
        Tag = 9
        Left = 12
        Top = 44
        Width = 326
        Height = 17
        Anchors = [akLeft, akTop, akRight]
        AutoSize = False
        Caption = 'Please enter a name for the new area and select a tileset.'
      end
      object lName: TLabel
        Tag = 10
        Left = 20
        Top = 87
        Width = 31
        Height = 13
        Caption = 'Name:'
      end
      object lTileSet: TLabel
        Tag = 11
        Left = 20
        Top = 124
        Width = 34
        Height = 13
        Caption = 'Tileset:'
      end
      object eName: TEdit
        Tag = 12
        Left = 76
        Top = 84
        Width = 145
        Height = 21
        TabOrder = 0
        OnChange = eNameChange
      end
      object lbTileSets: TListBox
        Tag = 13
        Left = 76
        Top = 117
        Width = 145
        Height = 199
        Anchors = [akLeft, akTop, akBottom]
        ItemHeight = 13
        TabOrder = 1
        OnClick = lbTileSetsClick
        OnDblClick = lbTileSetsDblClick
      end
    end
    object tsSize: TTabSheet
      Tag = -1
      ImageIndex = 1
      object lTitleSize: TLabel
        Tag = 14
        Left = 12
        Top = 12
        Width = 79
        Height = 20
        Caption = 'Area Size'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'MS Sans Serif'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lDescriptionSize: TLabel
        Tag = 15
        Left = 12
        Top = 44
        Width = 326
        Height = 17
        Anchors = [akLeft, akTop, akRight]
        AutoSize = False
        Caption = 'Please choose a size for the new area.'
      end
      object lWidth: TLabel
        Tag = 21
        Left = 112
        Top = 211
        Width = 28
        Height = 13
        Caption = 'Width'
      end
      object lHeight: TLabel
        Tag = 22
        Left = 32
        Top = 90
        Width = 31
        Height = 13
        Caption = 'Height'
      end
      object Image1: TImage
        Left = 88
        Top = 104
        Width = 100
        Height = 100
        Picture.Data = {
          07544269746D6170C6140000424DC61400000000000076000000280000006400
          0000640000000100040000000000501400000000000000000000100000000000
          0000000000000000800000800000008080008000000080008000808000008080
          8000C0C0C0000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
          FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFF0FFFF0FFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFF0FFFF0000FFFF
          FFFFFFFF0FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFF0FFF0FFFF0000FFFFFFFFFFFF0FF0FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          0FF0FFFF0000FFFFFFFFFFFF0F00000000000000000000000000000000000000
          000000000000000000000000000000000000000000F0FFFF0000FFFFFFFFFFFF
          0FF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0FF0FFFF0000FFFFFFFFFFFF0FFF0FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFF0FFFF
          0000FFFFFFFFFFFF0FFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFF0FFFF0000FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FF0000000FFF0000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000FFFF0000FFFFFFFFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFF000FFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFF0F0F0FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FF0FF0FF0FFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF
          F0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
          0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFF0FFFFFF0AAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAA0FFFF0000FF0FF0FF0FFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFF0
          F0F0FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFF000FFFFF0AAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAA0FFFF0000FFFFF0FFFFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0000FFFFFFFFFFFF
          0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          AAAAAAAAAAAAAAAAAAA0FFFF0000FF0000000FFF000000000000000000000000
          000000000000000000000000000000000000000000000000000000000000FFFF
          0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000}
        Transparent = True
      end
      object lbSize: TListBox
        Tag = 16
        Left = 220
        Top = 108
        Width = 121
        Height = 73
        ItemHeight = 13
        TabOrder = 4
        OnClick = lbSizeClick
        OnDblClick = lbSizeDblClick
      end
      object eWidth: TEdit
        Left = 112
        Top = 232
        Width = 33
        Height = 21
        TabOrder = 2
        Text = '2'
        OnEnter = eLengthWidthEnter
        OnExit = eLengthWidthExit
      end
      object udWidth: TUpDown
        Left = 145
        Top = 232
        Width = 12
        Height = 21
        Associate = eWidth
        Min = 2
        Max = 32
        Position = 2
        TabOrder = 3
        Wrap = False
      end
      object udHeight: TUpDown
        Left = 65
        Top = 112
        Width = 12
        Height = 21
        Associate = eHeight
        Min = 2
        Max = 32
        Position = 2
        TabOrder = 1
        Wrap = False
      end
      object eHeight: TEdit
        Left = 32
        Top = 112
        Width = 33
        Height = 21
        TabOrder = 0
        Text = '2'
        OnEnter = eLengthWidthEnter
        OnExit = eLengthWidthExit
      end
    end
    object tsFinish: TTabSheet
      Tag = -1
      ImageIndex = 2
      object lTitleFinish: TLabel
        Tag = 17
        Left = 12
        Top = 12
        Width = 49
        Height = 20
        Caption = 'Finish'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'MS Sans Serif'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object lDescriptionFinish: TLabel
        Tag = 18
        Left = 12
        Top = 44
        Width = 333
        Height = 45
        Anchors = [akLeft, akTop, akRight]
        AutoSize = False
        Caption = 
          'This area is now ready to be created. Click Finish to add the ar' +
          'ea to your module.'
        WordWrap = True
      end
      object xbLaunchAreaDialog: TCheckBox
        Tag = 19
        Left = 16
        Top = 272
        Width = 305
        Height = 17
        Caption = 'Launch Area Properties Dialog'
        TabOrder = 0
      end
      object xbOpenNewArea: TCheckBox
        Tag = 20
        Left = 16
        Top = 296
        Width = 305
        Height = 17
        Caption = 'Open Area in the Area Viewer'
        Checked = True
        State = cbChecked
        TabOrder = 1
      end
    end
  end
end
