object dlgSoundEdit: TdlgSoundEdit
  Tag = 6
  Left = 259
  Top = 116
  BorderStyle = bsDialog
  Caption = 'Sound Properties'
  ClientHeight = 543
  ClientWidth = 557
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnResize = FormResize
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object bOK: TButton
    Tag = 1
    Left = 395
    Top = 512
    Width = 75
    Height = 25
    Anchors = [akRight, akBottom]
    Caption = 'OK'
    TabOrder = 1
    OnClick = bOKClick
  end
  object bCancel: TButton
    Tag = 2
    Left = 475
    Top = 512
    Width = 75
    Height = 25
    Anchors = [akRight, akBottom]
    Cancel = True
    Caption = 'Cancel'
    TabOrder = 2
    OnClick = bCancelClick
  end
  object pcSound: TPageControl
    Left = 0
    Top = 0
    Width = 557
    Height = 505
    ActivePage = tsBasic
    Anchors = [akLeft, akTop, akRight, akBottom]
    TabOrder = 0
    object tsBasic: TTabSheet
      Tag = 10
      Caption = 'Basic'
      ImageIndex = 2
      object lPaletteCategory: TLabel
        Tag = 7
        Left = 16
        Top = 123
        Width = 42
        Height = 13
        Caption = 'Category'
      end
      object lLocName: TLabel
        Tag = 3
        Left = 16
        Top = 11
        Width = 28
        Height = 13
        Caption = 'Name'
      end
      object lTag: TLabel
        Tag = 15
        Left = 16
        Top = 35
        Width = 19
        Height = 13
        Caption = 'Tag'
      end
      object lGain: TLabel
        Tag = 59
        Left = 16
        Top = 436
        Width = 35
        Height = 13
        Caption = 'Volume'
      end
      object lVolumeMid: TLabel
        Tag = -1
        Left = 268
        Top = 451
        Width = 25
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '5'
      end
      object lVolumeMin: TLabel
        Tag = -1
        Left = 136
        Top = 451
        Width = 35
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '0'
      end
      object lVolumeMax: TLabel
        Tag = -1
        Left = 390
        Top = 451
        Width = 35
        Height = 18
        Alignment = taCenter
        AutoSize = False
        Caption = '10'
      end
      object lComments: TLabel
        Tag = 66
        Left = 16
        Top = 59
        Width = 49
        Height = 13
        Caption = 'Comments'
      end
      object pSoundList: TPanel
        Tag = -1
        Left = 8
        Top = 168
        Width = 241
        Height = 249
        BevelOuter = bvNone
        TabOrder = 0
        object lSoundList: TLabel
          Tag = 18
          Left = 8
          Top = 0
          Width = 102
          Height = 13
          Caption = 'List of Sounds to Play'
        end
        object bPlay: TBitBtn
          Tag = 20
          Left = 152
          Top = 24
          Width = 81
          Height = 25
          Caption = 'Play'
          TabOrder = 1
          OnClick = bPlayClick
          NumGlyphs = 2
        end
        object lbSounds: TListBox
          Tag = 19
          Left = 8
          Top = 16
          Width = 137
          Height = 233
          Anchors = [akLeft, akTop, akBottom]
          ItemHeight = 13
          MultiSelect = True
          TabOrder = 0
          OnClick = lbSoundsClick
          OnKeyDown = lbSoundsKeyDown
        end
        object bRemoveSound: TButton
          Tag = 22
          Left = 152
          Top = 136
          Width = 81
          Height = 25
          Caption = 'Remove'
          TabOrder = 4
          OnClick = bRemoveSoundClick
        end
        object bAdd: TButton
          Tag = 21
          Left = 152
          Top = 104
          Width = 81
          Height = 25
          Caption = 'Add Sounds...'
          TabOrder = 3
          OnClick = bAddClick
        end
        object bMoveDown: TButton
          Tag = 24
          Left = 152
          Top = 216
          Width = 81
          Height = 25
          Caption = 'Move Down'
          TabOrder = 6
          OnClick = bMoveDownClick
        end
        object bMoveUp: TButton
          Tag = 23
          Left = 152
          Top = 184
          Width = 81
          Height = 25
          Caption = 'Move Up'
          TabOrder = 5
          OnClick = bMoveUpClick
        end
        object bStop: TBitBtn
          Tag = 82
          Left = 152
          Top = 56
          Width = 81
          Height = 25
          Caption = 'Stop'
          TabOrder = 2
          OnClick = bStopClick
          NumGlyphs = 2
        end
      end
      object bPaletteCategory: TButton
        Tag = 9
        Left = 297
        Top = 120
        Width = 21
        Height = 21
        HelpContext = 7235
        Caption = '...'
        TabOrder = 1
        OnClick = bPaletteCategoryClick
      end
      object ePaletteCategory: TEdit
        Tag = 8
        Left = 117
        Top = 120
        Width = 180
        Height = 21
        HelpContext = 7235
        Color = clInactiveBorder
        ReadOnly = True
        TabOrder = 2
      end
      object bLocName: TButton
        Tag = 5
        Left = 297
        Top = 8
        Width = 21
        Height = 21
        HelpContext = 7234
        Caption = '...'
        TabOrder = 3
      end
      object eLocName: TEdit
        Tag = 4
        Left = 117
        Top = 8
        Width = 180
        Height = 21
        HelpContext = 7234
        TabOrder = 4
      end
      object eTag: TEdit
        Tag = 16
        Left = 117
        Top = 32
        Width = 180
        Height = 21
        HelpContext = 7182
        MaxLength = 32
        TabOrder = 5
        OnChange = eTagChange
      end
      object tbVolume: TTrackBar
        Tag = 60
        Left = 146
        Top = 433
        Width = 269
        Height = 19
        HelpContext = 7647
        Max = 127
        Orientation = trHorizontal
        Frequency = 1
        Position = 127
        SelEnd = 0
        SelStart = 0
        TabOrder = 6
        ThumbLength = 10
        TickMarks = tmBottomRight
        TickStyle = tsManual
        OnChange = tbVolumeChange
      end
      object eComments: TEdit
        Tag = -1
        Left = 117
        Top = 56
        Width = 180
        Height = 21
        HelpContext = 7182
        TabOrder = 7
        Visible = False
      end
      object bComments: TButton
        Tag = 71
        Left = 297
        Top = 56
        Width = 21
        Height = 21
        HelpContext = 7234
        Caption = '...'
        TabOrder = 8
        Visible = False
        OnClick = bCommentsClick
      end
      object mComments: TMemo
        Tag = -1
        Left = 117
        Top = 56
        Width = 284
        Height = 61
        MaxLength = 1024
        ScrollBars = ssVertical
        TabOrder = 9
      end
    end
    object tsPositioning: TTabSheet
      Tag = 46
      Caption = 'Positioning'
      ImageIndex = 3
      object pPositionalFlags: TPanel
        Tag = -1
        Left = 16
        Top = 8
        Width = 297
        Height = 49
        BevelOuter = bvNone
        TabOrder = 0
        object rbOmnipresent: TRadioButton
          Tag = 47
          Left = 0
          Top = 0
          Width = 292
          Height = 17
          HelpContext = 7643
          Anchors = [akLeft, akTop, akRight]
          Caption = 'Plays everywhere in area'
          TabOrder = 0
          OnClick = rbPositionalClick
        end
        object rbPositionalRandom: TRadioButton
          Tag = 48
          Left = 0
          Top = 16
          Width = 292
          Height = 17
          HelpContext = 7643
          Anchors = [akLeft, akTop, akRight]
          Caption = 'Plays from a random position each time it is played'
          TabOrder = 1
          OnClick = rbPositionalClick
        end
        object rbPositional: TRadioButton
          Tag = 49
          Left = 0
          Top = 33
          Width = 292
          Height = 17
          HelpContext = 7643
          Anchors = [akLeft, akTop, akRight]
          Caption = 'Plays from specific position'
          TabOrder = 2
          OnClick = rbPositionalClick
        end
      end
      object gbRadii: TGroupBox
        Tag = 68
        Left = 16
        Top = 72
        Width = 513
        Height = 131
        Caption = 'Volume Distances'
        TabOrder = 1
        object pPositionalRadii: TPanel
          Tag = -1
          Left = 8
          Top = 16
          Width = 497
          Height = 113
          BevelOuter = bvNone
          TabOrder = 0
          object imgRadii: TImage
            Left = 0
            Top = 5
            Width = 100
            Height = 100
            Picture.Data = {
              07544269746D6170C6140000424DC61400000000000076000000280000006400
              0000640000000100040000000000501400000000000000000000100000000000
              0000000000000000800000800000008080008000000080008000808000008080
              8000C0C0C0000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
              FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCC
              CCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCFFFFFFFFFCCCCCCFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFCCCFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFFFFFFFFFFFF
              FFFFFFFFCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFCFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFCFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFCFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFCCCCCFFFFFFFF000000000000000000000000000000000000000FFFF
              0000FFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFCCCCCFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF0000FFFFFFFFFFCFFFFFFFFF
              FFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFCF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFF
              FFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF0FFFFFFF0000FFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFF
              FFFFFFFFFFFFFFFCFFFFFFF000FFFFFF0000FFFFFFFFFCFFFFFFFFFFFFFFFFFF
              FFFFFCCFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFCFFFFFF0F
              0F0FFFFF0000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF
              FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFCFFFF0FF0FF0FFFF0000FFFFFFFFCFFF
              FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFF
              FFFFFFFFCFFFFFFF0FFFFFFF0000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFFF0FFFFFFF
              0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFF0FFFFFFF0000FFFFFFFCFFFFFFFFFFFF
              FFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF
              FCFFFFFF0FFFFFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFF0FFFFFFF0000FFFF
              FFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFF
              FFFFFFFFFFFFFFFFFCFFFFFF0FFFFFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFF
              CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFF0FF
              0FF0FFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFF0F0F0FFFFF0000FFFFFFCFFFFF
              FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF
              FFFFFFFFFFCFFFF000FFFFFF0000FFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFF0FFFFFFF
              0000FFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF0000FFFFFFCFFFFFFFFFFFFF
              FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
              FFCFFFFFFFFFFFFF0000FFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF
              FFCFFFF000000000000000000000000000000000000000000000FFFF0000FFFF
              FFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFF
              FFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF0000FFFFFFCFFFFFFFFFFFFFFFFFFFFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFF
              FFFFFFFF0000FFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFF0FFFFFFF0000FFFFFFCFFFFF
              FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF
              FFFFFFFFFFCFFFF000FFFFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFF0F0F0FFFFF
              0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFCFFFFFFFFFFFFFFFFFFFFCFFF0FF0FF0FFFF0000FFFFFFFCFFFFFFFFFFFF
              FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF
              FCFFFFFF0FFFFFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFF0FFFFFFF0000FFFF
              FFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFF
              FFFFFFFFFFFFFFFFFCFFFFFF0FFFFFFF0000FFFFFFFCFFFFFFFFFFFFFFFFFFFF
              FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFF
              0FFFFFFF0000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFCFFFFFFF0FFFFFFF0000FFFFFFFFCFFF
              FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFF
              FFFFFFFFCFFFFFFF0FFFFFFF0000FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFCFFF
              FFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFF0FFFFFFF
              0000FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFCC
              FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF0FFFFFFF0000FFFFFFFFFCFFFFFFFFFF
              FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFC
              FFFFFFFF0FFFFFFF0000FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFF
              FFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF0FFFFFFF0000FFFF
              FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFCFFFFFFFFFFFFF
              FFFFFFFFFFFFFFCFFFFFFFFF0FFFFFFF0000FFFFFFFFFFCFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFCCCCCFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFF
              0FFFFFFF0000FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFF
              CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFCFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF0FFFFFFF
              0000FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFCFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFF
              FFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF0FFFFFFF0000FFFF
              FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFCFFFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFFFCFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFF
              0FFFFFFF0000FFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
              FFFFFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFF0FFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
              FFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFF0FFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              CCFFFFFFFFFFFFFFFFFFFFFF0FFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFCCF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFF0FF
              0FF0FFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFF0F0F0FFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFF
              FFFFFFFFFFFFFFF000FFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCFFF
              FFFFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFFFFFFFFFFFFFFCCC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFCCCCCCFFFFFFFFFCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCC
              CCCCCCCFFFFFFFFFFF0000000000000000000000000000000000FFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000}
            Transparent = True
          end
          object lDistanceMax: TLabel
            Tag = 54
            Left = 105
            Top = 5
            Width = 163
            Height = 13
            Caption = 'Outer Radius / Cutoff Distance (m)'
          end
          object lDistanceMin: TLabel
            Tag = 56
            Left = 105
            Top = 61
            Width = 191
            Height = 13
            Caption = 'Inner Radius / Max Volume Distance (m)'
          end
          object lDistanceMinMid: TLabel
            Tag = -1
            Left = 297
            Top = 92
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '5.0'
            Visible = False
          end
          object lDistanceMinMin: TLabel
            Tag = -1
            Left = 147
            Top = 92
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '0.2'
            Visible = False
          end
          object lDistanceMinMax: TLabel
            Tag = -1
            Left = 447
            Top = 92
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '10.0'
            Visible = False
          end
          object eDistanceMax: TEdit
            Tag = 55
            Left = 105
            Top = 18
            Width = 43
            Height = 21
            HelpContext = 7644
            MaxLength = 6
            TabOrder = 0
            OnEnter = eEditUpDownEnter
            OnExit = eDistanceMaxExit
            OnKeyDown = eEditUpDownKeyDown
          end
          object udDistanceMax: TUpDown
            Tag = 55
            Left = 147
            Top = 20
            Width = 13
            Height = 19
            HelpContext = 7644
            Min = 0
            Max = 32000
            Increment = 10
            Position = 0
            TabOrder = 1
            Wrap = False
            OnClick = udDistanceMaxClick
          end
          object eDistanceMin: TEdit
            Tag = 57
            Left = 105
            Top = 74
            Width = 43
            Height = 21
            HelpContext = 7644
            Color = clBtnFace
            MaxLength = 6
            ReadOnly = True
            TabOrder = 2
            OnEnter = eEditUpDownEnter
            OnExit = eDistanceMinExit
            OnKeyDown = eEditUpDownKeyDown
          end
          object tbDistanceMin: TTrackBar
            Tag = 58
            Left = 157
            Top = 74
            Width = 315
            Height = 17
            HelpContext = 7644
            Enabled = False
            Max = 255
            Min = 2
            Orientation = trHorizontal
            Frequency = 1
            Position = 2
            SelEnd = 0
            SelStart = 0
            TabOrder = 3
            ThumbLength = 10
            TickMarks = tmBottomRight
            TickStyle = tsManual
            Visible = False
            OnChange = tbDistanceMinChange
          end
        end
      end
      object gbRandomRange: TGroupBox
        Tag = 69
        Left = 224
        Top = 216
        Width = 305
        Height = 169
        Caption = 'Random Range'
        TabOrder = 2
        object pPositionalRandomRanges: TPanel
          Tag = -1
          Left = 8
          Top = 21
          Width = 281
          Height = 143
          BevelOuter = bvNone
          TabOrder = 0
          object lRandomRangeX: TLabel
            Tag = 50
            Left = 1
            Top = 102
            Width = 144
            Height = 13
            Caption = 'West-East Random Range (m)'
          end
          object lRandomRangeY: TLabel
            Tag = 52
            Left = 105
            Top = 5
            Width = 152
            Height = 13
            Caption = 'North-South Random Range (m)'
          end
          object imgRandomRange: TImage
            Left = 0
            Top = 1
            Width = 100
            Height = 100
            Picture.Data = {
              07544269746D6170C6140000424DC61400000000000076000000280000006400
              0000640000000100040000000000501400000000000000000000100000000000
              0000000000000000800000800000008080008000000080008000808000008080
              8000C0C0C0000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
              FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF3D43FFFF0FFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFF0FFFFFFFFFFFF3D43FFFF
              0FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFF0FFF0FFFFFFFFFFFF3D43FFFF0FF0FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FF0FFFF
              FFFFFFFF3D43FFFF0F0000000000000000000000000000000000000000000000
              0000000000000000000000000000000000F0FFFFFFFFFFFF3D43FFFF0FF0FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0FF0FFFFFFFFFFFF3D43FFFF0FFF0FFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFF0FFFFFFFFFFFF
              3D43FFFF0FFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF0FFFF0FFFFFFFFFFFF3D43FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF3D43FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43FFFF000000000000000000000000
              000000000000000000000000000000000000000000000000000000000000FFF0
              000000FF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFFFFFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFF000FFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF0F0F0FFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFF0FF0FF0FF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              FF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF
              3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAA0FFFFFF0FFFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFF0FF0FF0FF3D43FFFF
              0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA0FFFF0F0F0FFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFF
              F000FFFF3D43FFFF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0FFFFFF0FFFFF3D43FFFF0AAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAA0FFFFFFFFFFFF3D43FFFF00000000000000000000000000000000
              0000000000000000000000000000000000000000000000000000FFF0000000FF
              3D43FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF3D43FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3D43}
            Transparent = True
          end
          object eRandomRangeX: TEdit
            Tag = 51
            Left = 1
            Top = 115
            Width = 43
            Height = 21
            HelpContext = 7646
            MaxLength = 6
            TabOrder = 2
            OnEnter = eEditUpDownEnter
            OnExit = eRandomRangeXExit
            OnKeyDown = eEditUpDownKeyDown
          end
          object udRandomRangeX: TUpDown
            Tag = 51
            Left = 44
            Top = 116
            Width = 13
            Height = 19
            HelpContext = 7646
            Min = 0
            Max = 32000
            Position = 0
            TabOrder = 3
            Wrap = False
            OnClick = udRandomRangeXClick
          end
          object eRandomRangeY: TEdit
            Tag = 53
            Left = 105
            Top = 18
            Width = 43
            Height = 21
            HelpContext = 7646
            MaxLength = 6
            TabOrder = 0
            OnEnter = eEditUpDownEnter
            OnExit = eRandomRangeYExit
            OnKeyDown = eEditUpDownKeyDown
          end
          object udRandomRangeY: TUpDown
            Tag = 53
            Left = 148
            Top = 19
            Width = 13
            Height = 19
            HelpContext = 7646
            Min = 0
            Max = 32000
            Position = 0
            TabOrder = 1
            Wrap = False
            OnClick = udRandomRangeYClick
          end
        end
      end
      object gbHeight: TGroupBox
        Tag = 70
        Left = 16
        Top = 216
        Width = 201
        Height = 129
        Caption = 'Height'
        TabOrder = 3
        object pPositionalHeight: TPanel
          Tag = -1
          Left = 8
          Top = 16
          Width = 186
          Height = 105
          BevelOuter = bvNone
          TabOrder = 0
          object lElevationZero: TLabel
            Tag = -1
            Left = 306
            Top = 58
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '0.0'
            Visible = False
          end
          object lElevationMin: TLabel
            Tag = -1
            Left = 160
            Top = 58
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '-10.0'
            Visible = False
          end
          object lElevationMax: TLabel
            Tag = -1
            Left = 453
            Top = 58
            Width = 35
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '10.0'
            Visible = False
          end
          object lElevation: TLabel
            Tag = 61
            Left = 105
            Top = 27
            Width = 48
            Height = 13
            Caption = 'Height (m)'
          end
          object imgHeight: TImage
            Left = 0
            Top = 0
            Width = 100
            Height = 100
            Picture.Data = {
              07544269746D6170C6140000424DC61400000000000076000000280000006400
              0000640000000100040000000000501400000000000000000000100000000000
              0000000000000000800000800000008080008000000080008000808000008080
              8000C0C0C0000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFF
              FF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFF22222222222222222222222
              22222222222222222222222222222222222222222222222222222FFFFFFFFFFF
              FFFFFFFF0000FFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFFFFFFFFFFFFF0000FFFFFFF2AAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAA2FFFFFFFFFFFFFFFFF0000FFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFFFFFFFFFFF
              0000FFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFFFFFFFFFF0000FFFFFFFFFF2AAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              A2FFFFFFFFFFFFFF0000FFFFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFFFFFFFF0000FFFF
              FFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAA2FFFFFFFFFFFF0000FFFFFFFFFFFFF2AAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFF
              FFFFFFFF0000FFFFFFFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0
              0000000000000000000AAAAAAAAAAAAAAAAAA2FFFFFFFFFF0000FFFFFFFFFFFF
              FFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAA2FFFFFFFFF0000FFFFFFFFFFFFFFFF2AAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFFF
              0000FFFFFFFFFFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              000AAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFFFF0000FFFFFFFFFFFFFFFFFF2A
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0A0A0AAAAAAAAAAAAAAAAAAAA
              AAAAAAAAA2FFFFFF0000FFFFFFFFFFFFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAA
              AAAAAAAAAAAAAA0AA0AA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFFF0000FFFF
              FFFFFFFFFFFFFFFF2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAA0AAA0AA
              AAAAAAAAAAAAAAAAAAAAAAAAAAA2FFFF0000FFFFFFFFFFFFFFFFFFFFF2AAAAAA
              AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
              AAAA2FFF0000FFFFFFFFFFFFFFFFFFFFFF222222222222222222222222222222
              2222222220222222222222222222222222222222222222FF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              F0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              F0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              F0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
              CCCCCCCCCCFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFFFFCCCFFFF0FFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFCCFFFFFFFFFFFFFFFFFCCFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFF
              FFFFFFFCC0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCF
              FFFFFFFFFFFFFFFFFFFFFFFFF0CCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFF
              F0FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFCCFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFF0FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFCFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFF0FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFCFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              F0FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFCFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFF0FFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFF0FFFFFF
              FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFCFFFF
              FFFFFFFFFFFFFFFFCCFFFFFCCFFFFFFFF0FFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFCCFFFFFFFF
              FCCFFFFFF0FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFCF0FFF0FFF0FFFFFFFCFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFCFF0FF0FF0FFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFCFF0
              F0F0FFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFCFFF000FFFFFFFFFFFCFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFCFFFF
              FFFFFFFFFFFFFCFFF0FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFF
              FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFF
              FFFFFFFFFFFCFFFFFFFFCFF00000000000000000000FFFCFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFCFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFCF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF
              FFFFCFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFCFFF
              FFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFCFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFCFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFF
              FFFFFFFFFFFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFCCFFFFFFFFFCCFFFFFFFFFFFFF
              FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFCFFFF
              FFFFFFFFFFFFFFFFCCFFFFFCCFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFCCCCCF
              FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFF
              FFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFCCFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFCCFFFFFFFFFFFFFFFFFCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCFFFFFFFFF
              FFCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000}
            Transparent = True
          end
          object eElevation: TEdit
            Tag = 62
            Left = 105
            Top = 40
            Width = 43
            Height = 21
            HelpContext = 7650
            MaxLength = 6
            TabOrder = 0
            OnEnter = eEditUpDownEnter
            OnExit = eElevationExit
          end
          object tbElevation: TTrackBar
            Tag = 63
            Left = 170
            Top = 40
            Width = 308
            Height = 17
            HelpContext = 7650
            Min = -10
            Orientation = trHorizontal
            Frequency = 1
            Position = 0
            SelEnd = 0
            SelStart = 0
            TabOrder = 1
            ThumbLength = 10
            TickMarks = tmBottomRight
            TickStyle = tsManual
            Visible = False
            OnChange = tbElevationChange
          end
        end
      end
    end
    object tsAdvanced: TTabSheet
      Tag = 11
      Caption = 'Advanced'
      ImageIndex = 1
      object lTemplateResRef: TLabel
        Tag = 12
        Left = 16
        Top = 11
        Width = 44
        Height = 13
        Caption = 'Template'
      end
      object lPitchVariation: TLabel
        Tag = 67
        Left = 16
        Top = 427
        Width = 115
        Height = 13
        Caption = 'Pitch Variation (octaves)'
      end
      object lPitchVariationMid: TLabel
        Tag = -1
        Left = 305
        Top = 455
        Width = 89
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '0.5'
      end
      object lPitchVariationMin: TLabel
        Tag = -1
        Left = 209
        Top = 455
        Width = 81
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '0'
      end
      object lPitchVariationMax: TLabel
        Tag = -1
        Left = 432
        Top = 455
        Width = 35
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '1.0'
      end
      object lVolumeVariation: TLabel
        Tag = 64
        Left = 16
        Top = 387
        Width = 79
        Height = 13
        Caption = 'Volume Variation'
      end
      object lVolumeVariationMin: TLabel
        Tag = -1
        Left = 168
        Top = 405
        Width = 35
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '0'
      end
      object lVolumeVariationMid: TLabel
        Tag = -1
        Left = 295
        Top = 405
        Width = 35
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '5'
      end
      object lVolumeVariationMax: TLabel
        Tag = -1
        Left = 424
        Top = 405
        Width = 31
        Height = 13
        Alignment = taCenter
        AutoSize = False
        Caption = '10'
      end
      object eTemplateResRef: TEdit
        Tag = 13
        Left = 117
        Top = 8
        Width = 180
        Height = 21
        HelpContext = 7236
        Color = clBtnFace
        MaxLength = 16
        ReadOnly = True
        TabOrder = 0
        OnChange = eTemplateResRefChange
      end
      object ePitchVariation: TEdit
        Tag = -1
        Left = 165
        Top = 426
        Width = 60
        Height = 21
        HelpContext = 58331
        MaxLength = 5
        TabOrder = 7
        OnEnter = eEditUpDownEnter
        OnExit = ePitchVariationExit
      end
      object tbPitchVariation: TTrackBar
        Left = 242
        Top = 429
        Width = 215
        Height = 17
        HelpContext = 58331
        Max = 100
        Orientation = trHorizontal
        Frequency = 1
        Position = 100
        SelEnd = 0
        SelStart = 0
        TabOrder = 8
        ThumbLength = 10
        TickMarks = tmBottomRight
        TickStyle = tsManual
        OnChange = tbPitchVariationChange
      end
      object bUpdateInstancesInArea: TButton
        Tag = 14
        Left = 297
        Top = 6
        Width = 180
        Height = 24
        HelpContext = 7338
        Caption = 'Update instances in area'
        TabOrder = 1
        OnClick = bUpdateInstancesInAreaClick
      end
      object xbActive: TCheckBox
        Tag = 25
        Left = 16
        Top = 42
        Width = 137
        Height = 17
        HelpContext = 7649
        Caption = 'Active'
        TabOrder = 2
        OnClick = xbActiveClick
      end
      object gbTimes: TGroupBox
        Tag = 26
        Left = 16
        Top = 64
        Width = 393
        Height = 145
        Caption = 'When to play'
        TabOrder = 3
        object pTimes: TPanel
          Tag = -1
          Left = 8
          Top = 16
          Width = 273
          Height = 67
          BevelOuter = bvNone
          TabOrder = 0
          object rbTimeAlways: TRadioButton
            Tag = 29
            Left = 0
            Top = 34
            Width = 265
            Height = 17
            HelpContext = 7648
            Anchors = [akLeft, akTop, akRight]
            Caption = 'Always'
            TabOrder = 2
            OnClick = rbTimeClick
          end
          object rbTimeNight: TRadioButton
            Tag = 28
            Left = 0
            Top = 17
            Width = 265
            Height = 17
            HelpContext = 7648
            Anchors = [akLeft, akTop, akRight]
            Caption = 'Night'
            TabOrder = 1
            OnClick = rbTimeClick
          end
          object rbTimeDay: TRadioButton
            Tag = 27
            Left = 0
            Top = 0
            Width = 265
            Height = 17
            HelpContext = 7648
            Anchors = [akLeft, akTop, akRight]
            Caption = 'Day'
            TabOrder = 0
            OnClick = rbTimeClick
          end
          object rbTimeSpecific: TRadioButton
            Tag = 72
            Left = 0
            Top = 51
            Width = 265
            Height = 17
            Anchors = [akLeft, akTop, akRight]
            Caption = 'Specific Hours'
            TabOrder = 3
            OnClick = rbTimeClick
          end
        end
        object pHoursToPlay: TPanel
          Tag = -1
          Left = 32
          Top = 88
          Width = 357
          Height = 47
          BevelOuter = bvNone
          TabOrder = 1
          object lAM: TLabel
            Tag = 73
            Left = 0
            Top = 16
            Width = 38
            Height = 13
            Caption = 'Morning'
          end
          object lPM: TLabel
            Tag = 74
            Left = 0
            Top = 32
            Width = 46
            Height = 13
            Caption = 'Afternoon'
          end
          object l12: TLabel
            Left = 63
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '12'
          end
          object l1: TLabel
            Left = 87
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '1'
          end
          object l2: TLabel
            Left = 111
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '2'
          end
          object l3: TLabel
            Left = 135
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '3'
          end
          object l4: TLabel
            Left = 159
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '4'
          end
          object l5: TLabel
            Left = 183
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '5'
          end
          object l6: TLabel
            Left = 207
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '6'
          end
          object l7: TLabel
            Left = 231
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '7'
          end
          object l8: TLabel
            Left = 255
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '8'
          end
          object l9: TLabel
            Left = 279
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '9'
          end
          object l10: TLabel
            Left = 303
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '10'
          end
          object l11: TLabel
            Left = 327
            Top = 0
            Width = 28
            Height = 13
            Alignment = taCenter
            AutoSize = False
            Caption = '11'
          end
          object xb12AM: TCheckBox
            Tag = -1
            Left = 72
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 0
          end
          object xb1AM: TCheckBox
            Tag = -1
            Left = 96
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 1
          end
          object xb2AM: TCheckBox
            Tag = -1
            Left = 120
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 2
          end
          object xb3AM: TCheckBox
            Tag = -1
            Left = 144
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 3
          end
          object xb4AM: TCheckBox
            Tag = -1
            Left = 168
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 4
          end
          object xb5AM: TCheckBox
            Tag = -1
            Left = 192
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 5
          end
          object xb6AM: TCheckBox
            Tag = -1
            Left = 216
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 6
          end
          object xb7AM: TCheckBox
            Tag = -1
            Left = 240
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 7
          end
          object xb8AM: TCheckBox
            Tag = -1
            Left = 264
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 8
          end
          object xb9AM: TCheckBox
            Tag = -1
            Left = 288
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 9
          end
          object xb10AM: TCheckBox
            Tag = -1
            Left = 312
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 10
          end
          object xb11AM: TCheckBox
            Tag = -1
            Left = 336
            Top = 16
            Width = 17
            Height = 17
            TabOrder = 11
          end
          object xb12PM: TCheckBox
            Tag = -1
            Left = 72
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 12
          end
          object xb1PM: TCheckBox
            Tag = -1
            Left = 96
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 13
          end
          object xb2PM: TCheckBox
            Tag = -1
            Left = 120
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 14
          end
          object xb3PM: TCheckBox
            Tag = -1
            Left = 144
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 15
          end
          object xb4PM: TCheckBox
            Tag = -1
            Left = 168
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 16
          end
          object xb5PM: TCheckBox
            Tag = -1
            Left = 192
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 17
          end
          object xb6PM: TCheckBox
            Tag = -1
            Left = 216
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 18
          end
          object xb7PM: TCheckBox
            Tag = -1
            Left = 240
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 19
          end
          object xb8PM: TCheckBox
            Tag = -1
            Left = 264
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 20
          end
          object xb9PM: TCheckBox
            Tag = -1
            Left = 288
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 21
          end
          object xb10PM: TCheckBox
            Tag = -1
            Left = 312
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 22
          end
          object xb11PM: TCheckBox
            Tag = -1
            Left = 336
            Top = 32
            Width = 17
            Height = 17
            TabOrder = 23
          end
        end
      end
      object gbPlayStyle: TGroupBox
        Tag = 76
        Left = 16
        Top = 216
        Width = 185
        Height = 73
        Caption = 'Play Style'
        TabOrder = 4
        object rbLooping: TRadioButton
          Tag = 31
          Left = 8
          Top = 50
          Width = 169
          Height = 17
          HelpContext = 7641
          Anchors = [akLeft, akTop, akRight]
          Caption = 'Seamlessly looping'
          TabOrder = 2
          OnClick = rbTypeClick
        end
        object rbContinuous: TRadioButton
          Tag = 78
          Left = 8
          Top = 33
          Width = 169
          Height = 17
          HelpContext = 7641
          Caption = 'Repeat'
          TabOrder = 1
          OnClick = rbTypeClick
        end
        object rbOnce: TRadioButton
          Tag = 77
          Left = 8
          Top = 16
          Width = 169
          Height = 17
          HelpContext = 7639
          Caption = 'Play Once'
          TabOrder = 0
          OnClick = rbTypeClick
        end
      end
      object gbPlayOrder: TGroupBox
        Tag = 79
        Left = 224
        Top = 224
        Width = 185
        Height = 57
        Caption = 'Play Order'
        TabOrder = 5
        object rbSequential: TRadioButton
          Tag = 80
          Left = 8
          Top = 16
          Width = 169
          Height = 17
          HelpContext = 7641
          Caption = 'Sequential'
          TabOrder = 0
        end
        object rbRandom: TRadioButton
          Tag = 81
          Left = 8
          Top = 32
          Width = 169
          Height = 17
          HelpContext = 7641
          Caption = 'Random'
          TabOrder = 1
        end
      end
      object gbInterval: TGroupBox
        Tag = 41
        Left = 16
        Top = 304
        Width = 305
        Height = 65
        Caption = 'Interval'
        TabOrder = 6
        object pPlayOrder: TPanel
          Tag = -1
          Left = 8
          Top = 16
          Width = 289
          Height = 43
          BevelOuter = bvNone
          TabOrder = 0
          object lIntervalVariation: TLabel
            Tag = 44
            Left = 1
            Top = 25
            Width = 128
            Height = 13
            Caption = 'Interval Variation (seconds)'
          end
          object lInterval: TLabel
            Tag = 42
            Left = 1
            Top = 3
            Width = 201
            Height = 13
            Caption = 'Interval between playing sounds (seconds)'
          end
          object eInterval: TEdit
            Tag = 43
            Left = 226
            Top = 0
            Width = 43
            Height = 21
            HelpContext = 7642
            MaxLength = 5
            TabOrder = 0
            OnEnter = eEditUpDownEnter
            OnExit = eIntervalExit
          end
          object eIntervalVariation: TEdit
            Tag = 45
            Left = 226
            Top = 22
            Width = 43
            Height = 21
            HelpContext = 7642
            MaxLength = 5
            TabOrder = 2
            OnEnter = eEditUpDownEnter
            OnExit = eIntervalVariationExit
          end
          object udIntervalVariation: TUpDown
            Tag = 45
            Left = 268
            Top = 23
            Width = 13
            Height = 19
            HelpContext = 7642
            Min = 0
            Increment = 10
            Position = 0
            TabOrder = 3
            Wrap = False
            OnClick = udIntervalVariationClick
          end
          object udInterval: TUpDown
            Tag = 43
            Left = 268
            Top = 1
            Width = 13
            Height = 19
            HelpContext = 7642
            Min = 0
            Increment = 10
            Position = 0
            TabOrder = 1
            Wrap = False
            OnClick = udIntervalClick
          end
        end
      end
      object pSoundPlayOptions: TPanel
        Tag = -1
        Left = 416
        Top = 104
        Width = 321
        Height = 161
        BevelOuter = bvNone
        TabOrder = 9
        Visible = False
        object gbOptionsMultipleOneShot: TGroupBox
          Tag = 36
          Left = 8
          Top = 64
          Width = 305
          Height = 89
          Caption = 'Options for playing multiple sounds'
          TabOrder = 0
          Visible = False
          object pPlayOptions: TPanel
            Tag = -1
            Left = 8
            Top = 16
            Width = 289
            Height = 65
            BevelOuter = bvNone
            TabOrder = 0
            object rbContinuousRandom: TRadioButton
              Tag = 37
              Left = 0
              Top = 0
              Width = 276
              Height = 17
              HelpContext = 7641
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Continously choose a new random sound to play'
              TabOrder = 0
              OnClick = rbPlayOptionsClick
            end
            object rbOnceRandom: TRadioButton
              Tag = 38
              Left = 0
              Top = 16
              Width = 276
              Height = 17
              HelpContext = 7641
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Play a randomly selected sound once'
              TabOrder = 1
              OnClick = rbPlayOptionsClick
            end
            object rbContinuousSequential: TRadioButton
              Tag = 39
              Left = 0
              Top = 32
              Width = 276
              Height = 17
              HelpContext = 7641
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Continuously play sounds in order'
              TabOrder = 2
              OnClick = rbPlayOptionsClick
            end
            object rbOnceSequential: TRadioButton
              Tag = 40
              Left = 0
              Top = 48
              Width = 276
              Height = 17
              HelpContext = 7641
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Play list in order once'
              TabOrder = 3
              OnClick = rbPlayOptionsClick
            end
          end
        end
        object gbOptionsSingleOneShot: TGroupBox
          Tag = 33
          Left = 8
          Top = 64
          Width = 305
          Height = 57
          Caption = 'Options for playing a single sound'
          TabOrder = 1
          Visible = False
          object pPlayOptionsSingle: TPanel
            Tag = -1
            Left = 8
            Top = 16
            Width = 289
            Height = 33
            BevelOuter = bvNone
            TabOrder = 0
            object rbContinuousSequentialSingle: TRadioButton
              Tag = 34
              Left = 0
              Top = 0
              Width = 276
              Height = 17
              HelpContext = 7640
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Continuously play sound'
              TabOrder = 0
              OnClick = rbPlayOptionsSingleClick
            end
            object rbOnceSequentialSingle: TRadioButton
              Tag = 36
              Left = 0
              Top = 16
              Width = 276
              Height = 17
              HelpContext = 7640
              Anchors = [akLeft, akTop, akRight]
              Caption = 'Play sound once'
              TabOrder = 1
              OnClick = rbPlayOptionsSingleClick
            end
          end
        end
        object gdLoopingOneShot: TGroupBox
          Tag = 30
          Left = 8
          Top = 0
          Width = 305
          Height = 57
          Caption = 'Type'
          TabOrder = 2
          Visible = False
          object pType: TPanel
            Tag = -1
            Left = 8
            Top = 16
            Width = 289
            Height = 33
            BevelOuter = bvNone
            TabOrder = 0
            object rbOneShot: TRadioButton
              Tag = 32
              Left = 0
              Top = 16
              Width = 281
              Height = 17
              HelpContext = 7639
              Anchors = [akLeft, akTop, akRight]
              Caption = 'One or more distinct sounds played individually'
              TabOrder = 0
              OnClick = rbTypeClick
            end
          end
        end
      end
      object tbVolumeVariation: TTrackBar
        Tag = 65
        Left = 178
        Top = 387
        Width = 269
        Height = 19
        HelpContext = 7658
        Max = 127
        Orientation = trHorizontal
        Frequency = 1
        Position = 25
        SelEnd = 0
        SelStart = 0
        TabOrder = 10
        ThumbLength = 10
        TickMarks = tmBottomRight
        TickStyle = tsManual
        OnChange = tbVolumeVariationChange
      end
      object bVariables: TButton
        Tag = 83
        Left = 368
        Top = 32
        Width = 105
        Height = 25
        HelpContext = 83316
        Caption = 'Variables...'
        TabOrder = 11
        OnClick = bVariablesClick
      end
    end
    object tsComments: TTabSheet
      Tag = 66
      Caption = 'Comments'
      ImageIndex = 2
      TabVisible = False
    end
  end
  object bDefaults: TButton
    Tag = 17
    Left = 7
    Top = 512
    Width = 75
    Height = 25
    Anchors = [akLeft, akBottom]
    Caption = 'Defaults'
    TabOrder = 3
    Visible = False
    OnClick = bDefaultsClick
  end
end
